[View in Colaboratory](https://colab.research.google.com/github/battlerhythm/tensorflow/blob/master/3.2%20Variable.ipynb)

In [1]:
import tensorflow as tf

# None은 크기가 정해지지 않았음을 의미합니다.
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [0]:
# 앞에서 텐서 모양을 (?, 3)으로 정의했으므로, 두번째 차원은 요소를 3개씩 가지고 있어야 합니다.
x_data = [[1, 2, 3], [4, 5, 6]]

In [0]:
# 정규분포(Normal Distribution)의 무작위값으로 초기화
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

# 원하는 값으로 초기화
# W = tf.Variable([0.1, 0.1], [0.2, 0.2], [0.3, 0.3])

In [0]:
# X와 W가 행렬이기 때문에 tf.matmul 함수를 사용합니다.
# 행렬이 아닐경우 단순히 곱셈 연산자(*)나 tf.mul함수를 사용하면 됩니다.
expr = tf.matmul(X, W) + b

In [5]:
sess = tf.Session()

# 앞에서 정의한 변수들을 초기화하는 함수입니다.
# 기존에 학습한 값들을 가져와서 사용하는 것이 아닌 처음 실행하는 것이라면,
# 연산을 실행하기 전에 반드시 이 함수를 이용해 변수들을 초기화해햐 합니다.
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== matmul(X, W) ===")
print(sess.run(tf.matmul(X, W), feed_dict={X: x_data}))

# 2 by 2 + 2 by 1 이 가능한 이유: Broadcasting semantics
# https://www.tensorflow.org/performance/xla/broadcasting
print("=== b ===")
print(sess.run(b))
print("=== expr ===")

# feed_dict 매개변수는 그래프를 실행할 때 사용할 입력값을 지정합니다.
# expr 수식에는 X, W, b를 사용했는데, 이중 X가 플레이스홀더라
# X에 값을 넣어주지 않으면 계산에 사용할 값이 없으므로 에러가 납니다.
# 따라서 미리 정의 해둔 x_data를 X의 값으로 넣어주었습니다.
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.09047401  0.17826337]
 [ 0.7478093   1.3657159 ]
 [ 0.5915431  -0.48106012]]
=== matmul(X, W) ===
[[3.1797738 1.4665148]
 [6.926409  4.655272 ]]
=== b ===
[[-1.4073021]
 [-0.3767064]]
=== expr ===
[[1.7724717  0.05921268]
 [6.549702   4.2785654 ]]
